server:
  port: 8080
  # address: 0.0.0.0
  #ssl:
  #  key-store: classpath:tv2.onlinetech.com.cn.jks
  #  key-password: z87786130

saltpasswd:
  salt1: 532ap.opgg
batchDelete:
  open: true

guns:
  swagger-open: true              #是否开启swagger (true/false)
  kaptcha-open: false             #是否开启登录时验证码 (true/false)
#  file-upload-path: d:/tmp       #文件上传目录(不配置的话为java.io.tmpdir目录)
  spring-session-open: false      #是否开启spring session,如果是多机环境需要开启(true/false)
  session-invalidate-time: 1800     #session失效时间(只在单机环境下生效，多机环境在SpringSessionConfig类中配置) 单位：秒
  session-validation-interval: 900  #多久检测一次失效的session(只u在单机环境下生效) 单位：秒

spring:
  profiles:
    active: @spring.active@
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /WEB-INF/view
    
  devtools:
    restart:
      enabled: false
      additional-paths: guns-admin/src/main/java
      exclude: static/**,WEB-INF/view/**
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
  mail:
    host: smtp.163.com
    username: 13065708090@163.com
    password: hyj78586421
    #password: WMMszmsl78586421
    default-encoding: UTF-8
    fromMail:
      addr: 13065708090@163.com




mybatis-plus:
  typeAliasesPackage: com.stylefeng.guns.modular.system.model

log:
  path: guns-logs

---
#mysql时区修改为CTT
spring:
  profiles: local
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/guns?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    username: root
    password: 123456
    db-name: guns #用来搜集数据库的所有表
    filters: wall,mergeStat
  #jackson:
  # default-property-inclusion: non_null

#多数据源情况的配置
#修改成自己的多数据源（第二个数据库） 并且开启多数据源 open: true
guns:
  muti-datasource:
    open: true
    url: jdbc:mysql://127.0.0.1:3306/sea_cms?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    username: root
    password: 123456
    dataSourceNames:
      - dataSourceGuns
      - dataSourceBiz

---

spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/guns?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    username: root
    password: 123456
    db-name: guns #用来搜集数据库的所有表
    filters: wall,mergeStat
---

spring:
  profiles: test
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/guns?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    username: root
    password: 123456
    filters: wall,mergeStat

---

spring:
  profiles: produce
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sql056779?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    username: sql056779
    password: 2ba5deb6
    db-name: sql056779 #用来搜集数据库的所有表
    filters: wall,mer

